### ISSUE TITLE
Typo Error

### ISSUE THREAD

**Issue by aniketsingh03** [vicky002/Charmander#3]
There are typo errors in README.md. One under the section "Why am I doing this", instead of "blot" it should be "bot" and the other in the end, it should be "built" instead of "build" imo.

**Comment by vicky002** [comment]
Hi @Partitioners,

Thanks for pointing this out. I fixed both typos. 
:+1: 

~ Vikesh

PS: Closing the issue. Feel free to create issues, if you find something broken. :slightly_smiling_face: :heart:
